--SCRIPT PARA MODELO SISTEMA DE VIAGEM

--CADASTRO DE USUARIO
CREATE TABLE CADASTRO_USUARIO(
	COD_USUARIO INT NOT NULL,
    NOME VARCHAR(50) NOT NULL,
    CPF INT NOT NULL,
    SENHA VARCHAR(16) NOT NULL,
);

--PK
ALTER TABLE CADASTRO_USUARIO ADD CONSTRAINT CADASTRO_USUARIO_PK
	PRIMARY KEY (COD_USUARIO);
    
--CADASTRO DE MOTORISTA
CREATE TABLE CADASTRO_MOTORISTA(
	COD_MOTORISTA INT NOT NULL,
    NOME VARCHAR(50) NOT NULL,
    CPF INT NOT NULL,
    RG VARCHAR(20) NOT NULL,
    CNH INT NOT NULL,
    TELEFONE INT NOT NULL,
    ENDERECO VARCHAR(50),    
);

--PK
ALTER TABLE CADASTRO_MOTORISTA ADD CONSTRAINT CADASTRO_MOTORISTA_PK
	PRIMARY KEY (COD_MOTORISTA);

--CADASTRO DE VEICULO
CREATE TABLE CADASTRO_VEICULO(
    COD_VEICULO INT NOT NULL,
    PLACA VARCHAR(7) NOT NULL,
    MARCA VARCHAR(20) NOT NULL,
    UF VARCHAR(20) NOT NULL,
    ANO INT NOT NULL, 
    TIPO_COMBUSTIVEL INT NOT NULL,
    QUANT_PASSAGEIRO INT NOT NULL
);

--PK
ALTER TABLE CADASTRO_VEICULO ADD CONSTRAINT CADASTRO_VEICULO_PK
	PRIMARY KEY (COD_VEICULO);

--AGENDAMENTO DE VIAGEM
CREATE TABLE AGENDAMENTO_VIAGEM(
	COD_VIAGEM INT NOT NULL,
    ENDERECO VARCHAR(50) NOT NULL,
    QUANT_PASSAGEIRO INT NOT NULL,
    DATA_SAIDA DATE NOT NULL,
    DATA_RETORNO DATE NOT NULL,
    HORA_SAIDA TIME NOT NULL,
    HORA_RETORNO TIME NOT NULL,
    STATUS_VIAGEM INT NOT NULL,
    VALOR_VIAGEM FLOAT NOT NULL,
    COD_VEICULO INT NOT NULL,
    COD_MOTORISTA INT NOT NULL
);

--PK
ALTER TABLE AGENDAMENTO_VIAGEM ADD CONSTRAINT AGENDAMENTO_VIAGEM_PK
	PRIMARY KEY (COD_VIAGEM);
    
ALTER TABLE AGENDAMENTO_VIAGEM ADD CONSTRAINT AGENDAMENTO_VIAGEM_VEIC_FK
	FOREIGN KEY (COD_VEICULO) REFERENCES CADASTRO_VEICULO (COD_VEICULO);
    
ALTER TABLE AGENDAMENTO_VIAGEM ADD CONSTRAINT AGENDAMENTO_VIAGEM_MOTORISTA_FK
	FOREIGN KEY (COD_MOTORISTA) REFERENCES CADASTRO_MOTORISTA (COD_MOTORISTA);